# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty
baseurl: 

# Setup
title:            Philip A. Nunoo
tagline:          'thanks for stopping by'
description:      'Welcome to my 127.0.0.1 (home) on the internet.'
url:              
safe: true

author:
  name:           'Philip Afful Nunoo'
  url:            https://twitter.com/Philip-Nunoo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/Philip-Nunoo/philipnunoo
  
facebook:
  url:            https://www.facebook.com/philip.nunoo
  
twitter:
  url:            http://twitter.com/philip_nunoo
  
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-50240657-1'



